export const ResponseMessages = {
  OTP_SENT: "OTP has been sent!",
  VERIFIED: "Your account has been verified successfully",
  ACCOUNT_CREATED: "Your account has been created successfully",
  LOGGED_IN: "Login successfully",
  PASSWORD_UPDATED: "Password updated successfully",
  PROFILE_UPDATED: "Profile updated successfully",
  PAYMENT_METHOD_REMOVED: "Payment method removed successfully",
  PAYMENT_METHOD_ADDED: "Payment method added successfully",
  PHONE_VERIFIED: "Phone number verified successfully",
  EMAIL_VERIFIED: "Email verified successfully",
  LISTING_CREATED: "Listing created successfully",
  LISTING_UPDATED: "Listing updated successfully",
  BOOKING_REQUESTED: "Booking request sent successfully",
  BOOKING_STATUS_UPDATED: "Booking status updated successfully",
  REVIEW_GIVEN: "Review submitted successfully",
  CONTACT_US: "Submitted successfully",
  BOOKING_CANCELED: "Booking cancelled successfully",
};
